{{- if .Values.ingress }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "app.name" . }}
  namespace: {{ include "app.namespace" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
    {{- with .Values.ingress.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.ingressClassName }}
  ingressclassName: {{ . }} 
  {{- end }}
  rules:
    - host: {{ .Values.ingress.hostname }}
      http:
        paths:
        {{- with .Values.ingress.extraPaths }}
          {{- tpl . $ | nindent 10 }}
        {{- end }}
          - path: {{ default "/" .Values.ingress.path }}
            pathType: {{ .Values.ingress.pathType }}
            backend:
              service:
                name: {{ include "app.name" . }}
                port:
                  number: {{- default 80 .Values.ingress.servicePort }}
    {{- range .Values.ingress.extraHosts }}
    - host: {{ .name | quote }}
      http:
        paths:
          - path: {{ default $.Values.ingress.path .path }}
            pathType: {{ default $.Values.ingress.pathType .pathType }}
            backend:
              service:
                name: {{ include "app.name" $ }}
                port:
                  number: {{- default 80 $.Values.ingress.servicePort .port }}
    {{- end }}
    {{- with .Values.ingress.extraRules }}
      {{- tpl . $ | nindent 4 }}
    {{- end }}
  {{- if or .Values.ingress.tls .Values.ingress.extraTls }}
  tls:
    - hosts:
      - {{ .Values.ingress.hostname }}
      {{- range .Values.ingress.extraHosts }}
      {{- if .name }}
      - {{ .name }}
      {{- end }}
      {{- end }}
      {{- with .Values.ingress.secretName }}
      secretName: {{ . }}
      {{- end }}
  {{- with .Values.server.ingress.extraTls }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
{{- end }}