{{- if .Values.secrets }}
{{- $name := include "app.name" . }}
{{- $namespace := include "app.namespace" . }}
{{- range .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}-{{ .name }}
  namespace: {{ $namespace }}
type: Opaque
data:
  {{- range $key, $value := .data }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
---
{{- end }}
{{- end }}